### ISSUE TITLE
Don't start on Linux Lenovo laptop with Ubuntu

### ISSUE THREAD

**Issue by agent-0007** [iperov/DeepFaceLive#122]
$ ./start.sh -c 
modinfo: ERROR: missing module or filename.

Starting with camera devices
--device=/dev/video0:/dev/video0 --device=/dev/video1:/dev/video1 --device=/dev/video2:/dev/video2 --device=/dev/video3:/dev/video3

Sending build context to Docker daemon  6.656kB
Step 1/15 : FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04
 ---> a5d351632b60
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> 01951e066ece
Step 3/15 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> cecd2f6d458e
Step 4/15 : ARG NV_VER
 ---> Using cache
 ---> c0178d87b280
Step 5/15 : RUN apt update
 ---> Using cache
 ---> 799433c85d36
Step 6/15 : RUN apt -y install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 curl ffmpeg git nano gnupg2 libsm6 wget unzip libxcb-icccm4 libxkbcommon-x11-0 libxcb-keysyms1 libxcb-icccm4 libxcb-render0 libxcb-render-util0 libxcb-image0
 ---> Using cache
 ---> e716c63425ea
Step 7/15 : RUN apt install -y python3 python3-pip
 ---> Using cache
 ---> 626dec7f3455
Step 8/15 : RUN ln -s /usr/bin/python3 /usr/bin/python
 ---> Using cache
 ---> c1e1a0ab8d9c
Step 9/15 : RUN git clone https://github.com/iperov/DeepFaceLive.git
 ---> Using cache
 ---> 4bc6a704e924
Step 10/15 : RUN python -m pip install --upgrade pip
 ---> Using cache
 ---> 180641963ee3
Step 11/15 : RUN python -m pip install onnxruntime-gpu==1.12.1 numpy==1.21.6 h5py numexpr protobuf==3.20.1 opencv-python==4.6.0.66 opencv-contrib-python==4.6.0.66 pyqt6==6.4.0 onnx==1.12.0 torch==1.10.0 torchvision==0.11.1
 ---> Using cache
 ---> 1bcd66e5c0b9
Step 12/15 : RUN apt install -y libnvidia-compute-$NV_VER
 ---> Using cache
 ---> ffd1d3f2761d
Step 13/15 : WORKDIR /app/DeepFaceLive
 ---> Using cache
 ---> 641d9261fac3
Step 14/15 : COPY example.sh example.sh
 ---> Using cache
 ---> 98cdf13cd73c
Step 15/15 : CMD ./example.sh
 ---> Using cache
 ---> ec02fb0387da
Successfully built ec02fb0387da
Successfully tagged deepfacelive:latest
access control disabled, clients can connect from any host
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by Kundanagrawalofficial** [comment]
This error message is indicating that there is a problem with the Docker container that is trying to run the script "start.sh" with the "-c" option.

It looks like the problem is related to the GPU driver. The error message says "could not select device driver "" with capabilities: [[gpu]]" which means that it is unable to find a GPU driver that matches the capabilities specified in the Docker container.

There could be a few reasons for this error:

The GPU driver is not properly installed on the host machine. Make sure that the GPU driver is up-to-date and properly installed on the host machine.

The version of the GPU driver on the host machine is not compatible with the version of the GPU driver specified in the Docker container. You might have to update the GPU driver in the container or use a different version of the container.

The host machine does not have a GPU or it is not being recognized by the system. Check if your machine have a GPU and it is properly connected and installed.

There's a problem with the Docker daemon. Try restarting the Docker daemon and see if that resolves the issue.

The Docker container is not properly configured for GPU support. Make sure that the Docker container is built with GPU support and that the correct GPU driver is specified in the container.

Try to resolve the issue by checking the GPU driver and its compatibility, check if the machine have a GPU, check the Docker daemon and the container configuration.

**Comment by iperov** [comment]
if you find solution, post info here
